version: '3'

# Define services
services:
    # Database Service (Mysql)
  db-service:
    image: mysql:5.6
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE : bancoapp
      MYSQL_USER : user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - backend 
# App backend service
  backend-service:
    # Configuration for building the docker image for the backend service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    depends_on: 
      - db-service # This service depends on mysql. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend: 